version: '3.8'

services:
  app:
    image: movies-db-backend
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    environment:
      DB_HOST: db
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: 'postgres:14.5'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: movies
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

volumes:
  postgres-data:
